name: conso
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  fluro: "^1.3.0"
  cupertino_icons: ^0.1.0
  path_provider: "^0.3.1"
  sqflite: any
  intl: any
  numberpicker: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/img/gas-station.jpeg
   - assets/img/car.jpeg
   - assets/img/speed.jpeg

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
