name: conso
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.3.1"
  sqflite: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
   - assets/img/gas-station.jpeg
   
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
