import 'package:flutter/material.dart' as material;
import './Utils/Service.dart';
import './Utils/StorageService.dart';
import 'package:dioc/dioc.dart';

// Pages
import 'Pages/AddDataPage.dart';
import 'Pages/HomePage.dart';
import 'Pages/LoginPage.dart';
import 'Pages/VehiclePage.dart';

final storageService = new StorageService();

@Provide.implemented(StorageService)
abstract class AppBootsrapper extends Bootsrapper {

  @Provide(Service, StorageService)
  Container environment();
}

/// Could be generated by <dioc_generator>

class _AppBootsrapper implements AppBootsrapper {
  Container base() {
    final container = new Container();
    container.register(StorageService, (c) => new StorageService());
    return container;
  }

  Container environment() {
    final container = base();
    return container;
  }
}

class AppBootsrapperBuilder  {
  static final AppBootsrapper instance = build();
  static AppBootsrapper build() => new _AppBootsrapper();
}

void main() {

  material.runApp(new material.MaterialApp(
    home: new HomePage(),
    routes: <String, material.WidgetBuilder>{
      "/AddDataPage":(material.BuildContext context) => new AddDataPage(),
      "/LoginPage":(material.BuildContext context) => new LoginPage(),
      "/VehiclePage":(material.BuildContext context) => new VehiclePage(),
    },
  ));
}